-- 공용 용어 사전 초기 데이터.
-- 분야 무관 용어(common-business)를 가장 앞에 두고, 산업별 분야가 뒤따른다.
-- 구독 행이 없는 Space는 모든 분야를 구독한 것으로 해석하므로 별도 백필은 하지 않는다.

insert into glossary_categories (id, slug, name, description, display_order) values
    ('glossary-category-common-business', 'common-business', '공통 비즈니스', '분야와 관계없이 쓰이는 일반 업무 용어.', 10),
    ('glossary-category-it-software', 'it-software', 'IT/소프트웨어', '소프트웨어 개발과 서비스 운영에서 쓰이는 용어.', 20),
    ('glossary-category-marketing-sales', 'marketing-sales', '마케팅/영업', '고객 확보와 판매 활동에서 쓰이는 용어.', 30),
    ('glossary-category-finance', 'finance', '금융', '재무, 회계, 금융 업무에서 쓰이는 용어.', 40),
    ('glossary-category-healthcare', 'healthcare', '의료', '진료와 의료기관 운영에서 쓰이는 용어.', 50),
    ('glossary-category-research', 'research', '연구', '연구 설계, 수행, 발표 과정에서 쓰이는 용어.', 60),
    ('glossary-category-education', 'education', '교육', '교육과정 운영과 학습 평가에서 쓰이는 용어.', 70),
    ('glossary-category-construction', 'construction', '건축', '설계, 시공, 현장 관리에서 쓰이는 용어.', 80),
    ('glossary-category-fashion-retail', 'fashion-retail', '패션/리테일', '상품 기획, 생산, 유통에서 쓰이는 용어.', 90)
on conflict (id) do nothing;

insert into shared_domain_terms (id, category_id, term, definition) values
    ('shared-term-common-business-001', 'glossary-category-common-business', 'KPI', '핵심성과지표(Key Performance Indicator). 목표를 얼마나 달성했는지 수치로 측정하기 위해 정한 지표.'),
    ('shared-term-common-business-002', 'glossary-category-common-business', 'OKR', '목표와 핵심결과(Objectives and Key Results). 도전적인 목표 하나에 측정 가능한 핵심 결과 몇 개를 붙여 관리하는 목표 설정 방식.'),
    ('shared-term-common-business-003', 'glossary-category-common-business', '마일스톤', '프로젝트 진행 과정에서 완료 여부를 확인하는 주요 중간 지점.'),
    ('shared-term-common-business-004', 'glossary-category-common-business', '리드타임', '요청이 접수된 시점부터 결과물이 전달되기까지 걸리는 총 시간.'),
    ('shared-term-common-business-005', 'glossary-category-common-business', '이해관계자', '프로젝트 결과에 영향을 주거나 영향을 받는 개인 또는 조직. 스테이크홀더라고도 한다.'),
    ('shared-term-common-business-006', 'glossary-category-common-business', 'R&R', '역할과 책임(Roles and Responsibilities). 업무를 누가 맡고 어디까지 책임지는지 정의한 것.'),
    ('shared-term-common-business-007', 'glossary-category-common-business', '아젠다', '회의에서 다룰 안건과 순서를 정리한 목록.'),
    ('shared-term-common-business-008', 'glossary-category-common-business', '액션 아이템', '회의에서 도출된 실행 과제. 담당자와 기한을 함께 정한다.'),
    ('shared-term-common-business-009', 'glossary-category-common-business', '팔로우업', '논의나 요청 이후 진행 상황을 확인하고 마무리하는 후속 조치.'),
    ('shared-term-common-business-010', 'glossary-category-common-business', '결재', '담당자가 올린 안건을 상위 권한자가 검토하고 승인하는 절차.'),
    ('shared-term-common-business-011', 'glossary-category-common-business', '품의', '의사결정권자의 승인을 받기 위해 사안을 정리해 올리는 문서 또는 그 절차.'),
    ('shared-term-common-business-012', 'glossary-category-common-business', '워크플로', '업무가 처리되는 단계와 순서를 정의한 흐름.'),
    ('shared-term-common-business-013', 'glossary-category-common-business', 'SLA', '서비스 수준 협약(Service Level Agreement). 제공할 서비스의 품질 기준과 미달 시 조치를 문서로 합의한 것.'),
    ('shared-term-common-business-014', 'glossary-category-common-business', '온보딩', '새 구성원이나 신규 고객이 조직 또는 제품에 적응하도록 돕는 초기 과정.'),
    ('shared-term-common-business-015', 'glossary-category-common-business', '벤치마킹', '다른 조직의 우수 사례를 조사해 자사 기준과 비교하고 개선점을 찾는 활동.'),
    ('shared-term-common-business-016', 'glossary-category-common-business', '백로그', '아직 처리하지 않고 쌓여 있는 업무나 요구사항 목록.'),
    ('shared-term-common-business-017', 'glossary-category-common-business', '리스크', '목표 달성을 위협할 수 있는 불확실한 사건이나 요인.'),
    ('shared-term-common-business-018', 'glossary-category-common-business', '데드라인', '업무를 반드시 마쳐야 하는 최종 기한.'),
    ('shared-term-common-business-019', 'glossary-category-common-business', 'TF', '태스크포스(Task Force). 특정 과제를 해결하기 위해 한시적으로 구성한 조직.'),
    ('shared-term-common-business-020', 'glossary-category-common-business', '캐파', '캐파시티(Capacity). 조직이나 설비가 일정 기간에 처리할 수 있는 최대 업무량.'),

    ('shared-term-it-software-001', 'glossary-category-it-software', 'API', '응용 프로그램 인터페이스(Application Programming Interface). 다른 소프트웨어가 기능이나 데이터를 사용할 수 있도록 정해둔 호출 규약.'),
    ('shared-term-it-software-002', 'glossary-category-it-software', '배포', '개발한 코드를 실제 사용자가 쓰는 환경에 올려 동작시키는 작업.'),
    ('shared-term-it-software-003', 'glossary-category-it-software', '롤백', '배포한 변경에 문제가 생겼을 때 직전의 정상 상태로 되돌리는 것.'),
    ('shared-term-it-software-004', 'glossary-category-it-software', 'CI/CD', '지속적 통합과 지속적 배포. 코드 변경을 자동으로 빌드·검증하고 배포까지 연결하는 파이프라인.'),
    ('shared-term-it-software-005', 'glossary-category-it-software', '스프린트', '애자일 개발에서 정해진 짧은 기간 동안 계획한 작업을 완료하는 반복 주기.'),
    ('shared-term-it-software-006', 'glossary-category-it-software', '스탠드업', '팀원이 진행 상황과 장애물을 짧게 공유하는 정기 회의.'),
    ('shared-term-it-software-007', 'glossary-category-it-software', '리팩터링', '겉으로 드러나는 동작은 그대로 두고 코드 내부 구조만 개선하는 작업.'),
    ('shared-term-it-software-008', 'glossary-category-it-software', '기술 부채', '빠른 구현을 위해 미룬 개선 작업이 쌓여 이후 개발 속도를 떨어뜨리는 상태.'),
    ('shared-term-it-software-009', 'glossary-category-it-software', '코드 리뷰', '다른 개발자가 변경한 코드를 검토해 결함과 개선점을 찾는 절차.'),
    ('shared-term-it-software-010', 'glossary-category-it-software', 'PR', '풀 리퀘스트(Pull Request). 작업한 코드 변경을 대상 브랜치에 반영해달라고 요청하는 단위.'),
    ('shared-term-it-software-011', 'glossary-category-it-software', '브랜치', '원본 코드에 영향을 주지 않고 따로 작업하기 위해 분기한 버전.'),
    ('shared-term-it-software-012', 'glossary-category-it-software', '머지', '분기해서 작업한 코드 변경을 다른 브랜치에 합치는 것.'),
    ('shared-term-it-software-013', 'glossary-category-it-software', '핫픽스', '운영 중 발생한 긴급 결함을 정규 배포 주기를 기다리지 않고 즉시 수정해 반영하는 것.'),
    ('shared-term-it-software-014', 'glossary-category-it-software', '장애', '서비스가 정상 동작하지 않아 사용자 이용에 영향을 주는 상태.'),
    ('shared-term-it-software-015', 'glossary-category-it-software', '포스트모템', '장애가 끝난 뒤 원인과 대응 과정을 정리해 재발 방지책을 도출하는 회고.'),
    ('shared-term-it-software-016', 'glossary-category-it-software', '로드밸런싱', '들어오는 요청을 여러 서버에 나누어 보내 부하를 분산하는 것.'),
    ('shared-term-it-software-017', 'glossary-category-it-software', '캐시', '반복해서 조회되는 데이터를 빠른 저장소에 미리 보관해 응답 속도를 높이는 기법.'),
    ('shared-term-it-software-018', 'glossary-category-it-software', '마이그레이션', '데이터나 시스템을 다른 구조 또는 환경으로 옮기는 작업.'),
    ('shared-term-it-software-019', 'glossary-category-it-software', '스키마', '데이터베이스에서 테이블과 컬럼, 제약조건의 구조를 정의한 것.'),
    ('shared-term-it-software-020', 'glossary-category-it-software', 'QA', '품질 보증(Quality Assurance). 결함을 찾고 품질 기준 충족 여부를 검증하는 활동.'),
    ('shared-term-it-software-021', 'glossary-category-it-software', '스테이징', '운영 환경과 최대한 비슷하게 구성해 배포 전 최종 검증을 하는 환경.'),
    ('shared-term-it-software-022', 'glossary-category-it-software', '온프레미스', '클라우드가 아니라 조직이 직접 보유하고 운영하는 서버 환경.'),
    ('shared-term-it-software-023', 'glossary-category-it-software', 'SDK', '소프트웨어 개발 키트(Software Development Kit). 특정 플랫폼용 개발에 필요한 라이브러리와 도구 묶음.'),
    ('shared-term-it-software-024', 'glossary-category-it-software', '레이턴시', '요청을 보낸 뒤 응답이 돌아오기까지 걸리는 지연 시간.'),

    ('shared-term-marketing-sales-001', 'glossary-category-marketing-sales', '리드', '제품에 관심을 보여 잠재 고객으로 확보한 연락처나 기업.'),
    ('shared-term-marketing-sales-002', 'glossary-category-marketing-sales', '전환율', '방문자나 리드 중 목표 행동(가입, 구매 등)까지 이어진 비율.'),
    ('shared-term-marketing-sales-003', 'glossary-category-marketing-sales', '퍼널', '인지부터 구매까지 고객이 거치는 단계를 깔때기 모양으로 표현한 모델.'),
    ('shared-term-marketing-sales-004', 'glossary-category-marketing-sales', 'CAC', '고객 획득 비용(Customer Acquisition Cost). 신규 고객 한 명을 확보하는 데 쓴 평균 비용.'),
    ('shared-term-marketing-sales-005', 'glossary-category-marketing-sales', 'LTV', '고객 생애 가치(Lifetime Value). 한 고객이 거래 기간 전체에 걸쳐 발생시키는 총 수익.'),
    ('shared-term-marketing-sales-006', 'glossary-category-marketing-sales', 'ROAS', '광고 수익률(Return On Ad Spend). 집행한 광고비 대비 발생한 매출의 비율.'),
    ('shared-term-marketing-sales-007', 'glossary-category-marketing-sales', '캠페인', '정해진 목표와 기간을 두고 실행하는 마케팅 활동 묶음.'),
    ('shared-term-marketing-sales-008', 'glossary-category-marketing-sales', '세그먼트', '특성이 비슷한 고객을 묶어 나눈 집단.'),
    ('shared-term-marketing-sales-009', 'glossary-category-marketing-sales', '타깃', '마케팅 활동에서 도달하려는 핵심 고객층.'),
    ('shared-term-marketing-sales-010', 'glossary-category-marketing-sales', '파이프라인', '영업 단계별로 진행 중인 거래 기회를 모아 관리하는 현황.'),
    ('shared-term-marketing-sales-011', 'glossary-category-marketing-sales', 'CRM', '고객 관계 관리(Customer Relationship Management). 고객 정보와 접점 이력을 관리하는 체계 또는 도구.'),
    ('shared-term-marketing-sales-012', 'glossary-category-marketing-sales', '이탈률', '일정 기간에 서비스 이용을 중단한 고객의 비율.'),
    ('shared-term-marketing-sales-013', 'glossary-category-marketing-sales', '리텐션', '확보한 고객이 계속 서비스를 이용하도록 유지하는 것, 또는 그 유지 비율.'),
    ('shared-term-marketing-sales-014', 'glossary-category-marketing-sales', 'A/B 테스트', '두 가지 안을 무작위로 나눠 노출하고 성과를 비교해 더 나은 쪽을 선택하는 실험.'),
    ('shared-term-marketing-sales-015', 'glossary-category-marketing-sales', '인바운드', '콘텐츠나 검색을 통해 고객이 먼저 찾아오게 만드는 마케팅 방식.'),
    ('shared-term-marketing-sales-016', 'glossary-category-marketing-sales', '아웃바운드', '기업이 잠재 고객에게 먼저 접촉해 수요를 만드는 영업·마케팅 방식.'),
    ('shared-term-marketing-sales-017', 'glossary-category-marketing-sales', '객단가', '고객 한 명이 한 번 거래할 때 지출하는 평균 금액.'),
    ('shared-term-marketing-sales-018', 'glossary-category-marketing-sales', '노출수', '광고나 콘텐츠가 사용자 화면에 표시된 횟수.'),
    ('shared-term-marketing-sales-019', 'glossary-category-marketing-sales', 'CTR', '클릭률(Click Through Rate). 노출 대비 클릭이 발생한 비율.'),
    ('shared-term-marketing-sales-020', 'glossary-category-marketing-sales', '프로모션', '할인이나 증정 등으로 단기간에 구매를 유도하는 판촉 활동.'),

    ('shared-term-finance-001', 'glossary-category-finance', '유동성', '자산을 큰 손실 없이 빠르게 현금으로 바꿀 수 있는 정도.'),
    ('shared-term-finance-002', 'glossary-category-finance', '자기자본', '총자산에서 부채를 뺀, 주주에게 귀속되는 자본.'),
    ('shared-term-finance-003', 'glossary-category-finance', '부채비율', '자기자본 대비 부채의 비율. 재무 안정성을 판단하는 지표로 쓴다.'),
    ('shared-term-finance-004', 'glossary-category-finance', '영업이익', '매출액에서 매출원가와 판매비·관리비를 뺀, 본업에서 발생한 이익.'),
    ('shared-term-finance-005', 'glossary-category-finance', '당기순이익', '모든 수익에서 모든 비용과 법인세를 뺀 최종 이익.'),
    ('shared-term-finance-006', 'glossary-category-finance', 'EBITDA', '이자, 세금, 감가상각비를 빼기 전의 영업이익. 기업의 현금 창출력을 비교할 때 쓴다.'),
    ('shared-term-finance-007', 'glossary-category-finance', 'ROE', '자기자본이익률(Return On Equity). 자기자본 대비 당기순이익의 비율.'),
    ('shared-term-finance-008', 'glossary-category-finance', '현금흐름', '일정 기간에 실제로 들어오고 나간 현금의 움직임.'),
    ('shared-term-finance-009', 'glossary-category-finance', '손익분기점', '매출과 총비용이 같아져 이익도 손실도 발생하지 않는 지점.'),
    ('shared-term-finance-010', 'glossary-category-finance', '감가상각', '자산의 취득원가를 사용 기간에 나누어 비용으로 인식하는 회계 처리.'),
    ('shared-term-finance-011', 'glossary-category-finance', '충당금', '미래에 발생할 것으로 예상되는 손실이나 비용에 대비해 미리 잡아두는 금액.'),
    ('shared-term-finance-012', 'glossary-category-finance', '헤지', '가격 변동으로 인한 손실 가능성을 줄이기 위해 반대 방향의 거래를 함께 잡는 것.'),
    ('shared-term-finance-013', 'glossary-category-finance', '여신', '금융기관이 고객에게 자금을 빌려주는 것.'),
    ('shared-term-finance-014', 'glossary-category-finance', '수신', '금융기관이 고객으로부터 예금 등의 자금을 받는 것.'),
    ('shared-term-finance-015', 'glossary-category-finance', '담보', '채무를 갚지 못할 때를 대비해 채권자에게 제공하는 자산이나 권리.'),
    ('shared-term-finance-016', 'glossary-category-finance', '실사', '거래나 투자에 앞서 대상의 재무·법률 상태를 직접 조사해 확인하는 절차.'),
    ('shared-term-finance-017', 'glossary-category-finance', 'IR', '투자자 관계(Investor Relations). 투자자에게 경영 성과와 전망을 알리는 활동.'),
    ('shared-term-finance-018', 'glossary-category-finance', '컴플라이언스', '법규와 내부 규정을 지키도록 관리하고 점검하는 준법 관리 체계.'),
    ('shared-term-finance-019', 'glossary-category-finance', '결산', '일정 기간의 거래를 마감해 재무제표를 확정하는 절차.'),
    ('shared-term-finance-020', 'glossary-category-finance', '회계연도', '재무제표 작성의 기준이 되는 1년 단위 회계 기간.'),

    ('shared-term-healthcare-001', 'glossary-category-healthcare', '진료', '의료인이 환자의 상태를 진찰하고 치료하는 행위.'),
    ('shared-term-healthcare-002', 'glossary-category-healthcare', '문진', '환자에게 증상, 병력, 생활 습관을 물어 진단에 필요한 정보를 얻는 진찰 방법.'),
    ('shared-term-healthcare-003', 'glossary-category-healthcare', '처방', '의사가 환자에게 필요한 약이나 치료를 지시하는 것.'),
    ('shared-term-healthcare-004', 'glossary-category-healthcare', '예후', '질병의 앞으로의 경과와 결과에 대한 의학적 전망.'),
    ('shared-term-healthcare-005', 'glossary-category-healthcare', '병력', '환자가 과거에 앓았던 질병과 치료 이력.'),
    ('shared-term-healthcare-006', 'glossary-category-healthcare', '소견', '검사나 진찰 결과에 대한 의료인의 판단 의견.'),
    ('shared-term-healthcare-007', 'glossary-category-healthcare', '판독', '영상 검사 결과를 전문의가 분석해 소견을 내는 것.'),
    ('shared-term-healthcare-008', 'glossary-category-healthcare', '협진', '여러 진료과가 함께 한 환자의 진단과 치료 방침을 논의하는 것.'),
    ('shared-term-healthcare-009', 'glossary-category-healthcare', '전원', '환자를 다른 의료기관으로 옮겨 진료를 이어가게 하는 것.'),
    ('shared-term-healthcare-010', 'glossary-category-healthcare', '외래', '입원하지 않고 병원을 방문해 진료받는 형태.'),
    ('shared-term-healthcare-011', 'glossary-category-healthcare', '입원', '치료를 위해 의료기관에 일정 기간 머무르는 것.'),
    ('shared-term-healthcare-012', 'glossary-category-healthcare', '퇴원', '입원 치료를 마치고 의료기관을 나가는 것.'),
    ('shared-term-healthcare-013', 'glossary-category-healthcare', 'EMR', '전자의무기록(Electronic Medical Record). 환자의 진료 기록을 전자 형태로 관리하는 시스템.'),
    ('shared-term-healthcare-014', 'glossary-category-healthcare', '활력징후', '체온, 맥박, 호흡, 혈압처럼 생명 유지 상태를 나타내는 기본 측정값. 바이탈이라고도 한다.'),
    ('shared-term-healthcare-015', 'glossary-category-healthcare', '금기', '특정 상태의 환자에게 해당 약물이나 처치를 사용해서는 안 되는 경우.'),
    ('shared-term-healthcare-016', 'glossary-category-healthcare', '부작용', '약물이나 치료가 의도한 효과 외에 일으키는 바람직하지 않은 반응.'),
    ('shared-term-healthcare-017', 'glossary-category-healthcare', '임상시험', '새로운 약이나 치료법의 안전성과 유효성을 사람을 대상으로 검증하는 연구.'),
    ('shared-term-healthcare-018', 'glossary-category-healthcare', 'IRB', '기관생명윤리위원회(Institutional Review Board). 사람을 대상으로 하는 연구의 윤리성과 안전성을 심의하는 기구.'),
    ('shared-term-healthcare-019', 'glossary-category-healthcare', '감염관리', '의료기관 안에서 감염이 발생하고 퍼지는 것을 예방하고 통제하는 활동.'),
    ('shared-term-healthcare-020', 'glossary-category-healthcare', '수가', '의료 행위나 약제에 대해 정해진 보험 지급 가격.'),

    ('shared-term-research-001', 'glossary-category-research', '선행연구', '다루려는 주제에 대해 이미 수행되어 발표된 기존 연구.'),
    ('shared-term-research-002', 'glossary-category-research', '가설', '검증하려는 관계나 결과를 미리 진술한 명제.'),
    ('shared-term-research-003', 'glossary-category-research', '표본', '전체 모집단에서 조사를 위해 뽑은 일부 대상.'),
    ('shared-term-research-004', 'glossary-category-research', '모집단', '연구가 결론을 적용하려는 전체 대상 집단.'),
    ('shared-term-research-005', 'glossary-category-research', '변수', '연구에서 값이 달라질 수 있는 측정 대상 요인.'),
    ('shared-term-research-006', 'glossary-category-research', '통제변수', '결과에 영향을 줄 수 있어 값을 일정하게 고정해두는 변수.'),
    ('shared-term-research-007', 'glossary-category-research', '유의수준', '통계 검정에서 귀무가설을 기각할지 판단하는 기준이 되는 확률값.'),
    ('shared-term-research-008', 'glossary-category-research', '정성연구', '인터뷰나 관찰처럼 수치화하기 어려운 자료로 현상을 해석하는 연구 방법.'),
    ('shared-term-research-009', 'glossary-category-research', '정량연구', '수치 자료를 통계로 분석해 결론을 도출하는 연구 방법.'),
    ('shared-term-research-010', 'glossary-category-research', '재현성', '같은 방법으로 다시 수행했을 때 같은 결과가 나오는 정도.'),
    ('shared-term-research-011', 'glossary-category-research', '피어리뷰', '동료 연구자가 논문의 타당성과 기여도를 심사하는 절차.'),
    ('shared-term-research-012', 'glossary-category-research', '인용', '다른 연구의 내용이나 결과를 출처를 밝히고 가져다 쓰는 것.'),
    ('shared-term-research-013', 'glossary-category-research', '초록', '논문의 목적, 방법, 결과, 결론을 짧게 요약한 글.'),
    ('shared-term-research-014', 'glossary-category-research', '연구윤리', '연구 수행과 발표 과정에서 지켜야 할 정직성과 책임의 기준.'),
    ('shared-term-research-015', 'glossary-category-research', '표절', '다른 사람의 저작이나 아이디어를 출처를 밝히지 않고 자기 것처럼 사용하는 행위.'),
    ('shared-term-research-016', 'glossary-category-research', '데이터셋', '분석에 사용하기 위해 정리한 자료의 모음.'),
    ('shared-term-research-017', 'glossary-category-research', '전처리', '분석에 앞서 데이터의 결측치, 오류, 형식을 정리하는 작업.'),
    ('shared-term-research-018', 'glossary-category-research', '편향', '표본 선정이나 측정 과정의 문제로 결과가 한쪽으로 치우치는 것.'),
    ('shared-term-research-019', 'glossary-category-research', '연구계획서', '연구 목적, 방법, 일정, 예산을 정리해 승인이나 지원을 요청하는 문서.'),
    ('shared-term-research-020', 'glossary-category-research', '중간보고', '연구 기간 중 진행 상황과 잠정 결과를 정리해 제출하는 보고.'),

    ('shared-term-education-001', 'glossary-category-education', '커리큘럼', '교육 목표에 따라 배울 내용과 순서를 체계적으로 짜놓은 교육과정.'),
    ('shared-term-education-002', 'glossary-category-education', '학습목표', '수업이 끝났을 때 학습자가 도달해야 할 상태를 구체적으로 기술한 것.'),
    ('shared-term-education-003', 'glossary-category-education', '형성평가', '학습이 진행되는 중에 이해도를 확인하고 수업을 조정하기 위해 하는 평가.'),
    ('shared-term-education-004', 'glossary-category-education', '총괄평가', '학습이 끝난 뒤 성취 수준을 종합적으로 판정하는 평가.'),
    ('shared-term-education-005', 'glossary-category-education', '루브릭', '평가 항목과 수준별 기준을 표로 정리한 채점 기준표.'),
    ('shared-term-education-006', 'glossary-category-education', '피드백', '학습자의 수행에 대해 개선 방향을 알려주는 정보 제공.'),
    ('shared-term-education-007', 'glossary-category-education', '블렌디드 러닝', '대면 수업과 온라인 학습을 결합해 운영하는 교육 방식.'),
    ('shared-term-education-008', 'glossary-category-education', '비대면 수업', '학습자와 교수자가 같은 공간에 있지 않고 온라인으로 진행하는 수업.'),
    ('shared-term-education-009', 'glossary-category-education', 'LMS', '학습관리시스템(Learning Management System). 수강, 콘텐츠, 평가, 이력을 관리하는 시스템.'),
    ('shared-term-education-010', 'glossary-category-education', '이수', '정해진 교육과정을 요건에 맞게 마치는 것.'),
    ('shared-term-education-011', 'glossary-category-education', '수료', '교육과정을 모두 이수했음을 공식적으로 인정받는 것.'),
    ('shared-term-education-012', 'glossary-category-education', '학점', '이수한 교과목의 학습량을 나타내는 단위.'),
    ('shared-term-education-013', 'glossary-category-education', '출석률', '전체 수업 횟수 대비 실제로 참석한 비율.'),
    ('shared-term-education-014', 'glossary-category-education', '교안', '수업 진행 내용과 순서를 미리 정리한 교수 계획 문서.'),
    ('shared-term-education-015', 'glossary-category-education', '멘토링', '경험이 많은 사람이 학습자의 성장을 지속적으로 돕는 활동.'),
    ('shared-term-education-016', 'glossary-category-education', '역량', '특정 과업을 수행하는 데 필요한 지식, 기술, 태도의 총합.'),
    ('shared-term-education-017', 'glossary-category-education', '자기주도학습', '학습자가 스스로 목표와 방법을 정해 진행하는 학습.'),
    ('shared-term-education-018', 'glossary-category-education', '보충학습', '목표 수준에 도달하지 못한 학습자를 대상으로 추가로 제공하는 학습.'),
    ('shared-term-education-019', 'glossary-category-education', '학사일정', '학기 시작, 시험, 방학 등 학교 운영의 주요 일정.'),
    ('shared-term-education-020', 'glossary-category-education', '교육수요조사', '어떤 교육이 필요한지 대상자에게 조사해 파악하는 활동.'),

    ('shared-term-construction-001', 'glossary-category-construction', '설계도서', '도면, 시방서, 계산서 등 설계 내용을 담은 문서 일체.'),
    ('shared-term-construction-002', 'glossary-category-construction', '시방서', '도면으로 표현하기 어려운 자재, 공법, 품질 기준을 글로 정한 문서.'),
    ('shared-term-construction-003', 'glossary-category-construction', '공정률', '전체 공사량 대비 현재까지 완료된 비율.'),
    ('shared-term-construction-004', 'glossary-category-construction', '공정표', '공사의 작업 순서와 기간을 일정으로 정리한 계획표.'),
    ('shared-term-construction-005', 'glossary-category-construction', '착공', '공사를 시작하는 것.'),
    ('shared-term-construction-006', 'glossary-category-construction', '준공', '공사를 모두 마쳐 건축물을 완성하는 것.'),
    ('shared-term-construction-007', 'glossary-category-construction', '감리', '공사가 설계도서와 관계 법령대로 시공되는지 확인하고 지도하는 업무.'),
    ('shared-term-construction-008', 'glossary-category-construction', '시공사', '실제로 공사를 수행하는 건설 업체.'),
    ('shared-term-construction-009', 'glossary-category-construction', '발주처', '공사를 의뢰하고 대금을 지급하는 주체.'),
    ('shared-term-construction-010', 'glossary-category-construction', '하도급', '원도급자가 맡은 공사의 일부를 다른 업체에 다시 맡기는 것.'),
    ('shared-term-construction-011', 'glossary-category-construction', '설계변경', '공사 중 여건이 달라져 당초 설계 내용을 바꾸는 것.'),
    ('shared-term-construction-012', 'glossary-category-construction', '내역서', '공사에 들어가는 항목별 수량과 단가, 금액을 정리한 문서.'),
    ('shared-term-construction-013', 'glossary-category-construction', '실행예산', '시공사가 실제 공사 수행을 기준으로 산정한 내부 예산.'),
    ('shared-term-construction-014', 'glossary-category-construction', '기성', '공사가 진행된 만큼 인정받아 청구하고 지급받는 대금.'),
    ('shared-term-construction-015', 'glossary-category-construction', '하자보수', '준공 후 발견된 결함을 시공자가 책임지고 고치는 것.'),
    ('shared-term-construction-016', 'glossary-category-construction', '안전관리계획', '공사 중 재해를 예방하기 위해 위험 요인과 대책을 정리한 계획.'),
    ('shared-term-construction-017', 'glossary-category-construction', '골조', '건축물의 하중을 지탱하는 기본 구조체.'),
    ('shared-term-construction-018', 'glossary-category-construction', '마감', '골조 위에 바닥, 벽, 천장 등을 시공해 최종 표면을 완성하는 공정.'),
    ('shared-term-construction-019', 'glossary-category-construction', '인허가', '건축 행위를 하기 위해 관계 기관의 허가와 승인을 받는 절차.'),
    ('shared-term-construction-020', 'glossary-category-construction', '현장회의', '공사 현장에서 발주처, 감리, 시공사가 진행 상황과 문제를 협의하는 회의.'),

    ('shared-term-fashion-retail-001', 'glossary-category-fashion-retail', 'SS', '봄·여름 시즌(Spring/Summer). 해당 시즌에 판매할 상품 라인을 가리킨다.'),
    ('shared-term-fashion-retail-002', 'glossary-category-fashion-retail', 'FW', '가을·겨울 시즌(Fall/Winter). 해당 시즌에 판매할 상품 라인을 가리킨다.'),
    ('shared-term-fashion-retail-003', 'glossary-category-fashion-retail', 'MD', '머천다이저(Merchandiser). 상품 기획, 구성, 판매 계획을 담당하는 직무.'),
    ('shared-term-fashion-retail-004', 'glossary-category-fashion-retail', '시즌오프', '시즌이 끝나가는 시점에 남은 재고를 정리하기 위해 할인 판매하는 것.'),
    ('shared-term-fashion-retail-005', 'glossary-category-fashion-retail', 'SKU', '재고 관리 최소 단위(Stock Keeping Unit). 색상과 사이즈까지 구분한 개별 상품 코드.'),
    ('shared-term-fashion-retail-006', 'glossary-category-fashion-retail', '발주', '필요한 상품 수량을 정해 공급처에 주문하는 것.'),
    ('shared-term-fashion-retail-007', 'glossary-category-fashion-retail', '입고', '주문한 상품이 창고나 매장에 들어오는 것.'),
    ('shared-term-fashion-retail-008', 'glossary-category-fashion-retail', '재고회전율', '일정 기간에 재고가 몇 번 판매되어 소진되었는지 나타내는 지표.'),
    ('shared-term-fashion-retail-009', 'glossary-category-fashion-retail', '소진율', '확보한 물량 중 실제로 판매된 비율.'),
    ('shared-term-fashion-retail-010', 'glossary-category-fashion-retail', '리오더', '반응이 좋은 상품을 추가로 다시 발주하는 것.'),
    ('shared-term-fashion-retail-011', 'glossary-category-fashion-retail', '원가율', '판매가에서 원가가 차지하는 비율.'),
    ('shared-term-fashion-retail-012', 'glossary-category-fashion-retail', '마진율', '판매가에서 원가를 뺀 이익이 판매가에서 차지하는 비율.'),
    ('shared-term-fashion-retail-013', 'glossary-category-fashion-retail', '컬렉션', '하나의 콘셉트로 기획해 함께 선보이는 상품 묶음.'),
    ('shared-term-fashion-retail-014', 'glossary-category-fashion-retail', '룩북', '상품의 착장 이미지를 모아 보여주는 홍보용 자료.'),
    ('shared-term-fashion-retail-015', 'glossary-category-fashion-retail', '샘플', '양산에 앞서 디자인과 품질을 확인하기 위해 만든 시제품.'),
    ('shared-term-fashion-retail-016', 'glossary-category-fashion-retail', '패턴', '옷을 재단하기 위해 부위별 모양과 치수를 그린 본.'),
    ('shared-term-fashion-retail-017', 'glossary-category-fashion-retail', '원부자재', '원단과 단추, 지퍼 등 상품 제작에 들어가는 재료.'),
    ('shared-term-fashion-retail-018', 'glossary-category-fashion-retail', '택', '상품에 부착해 품번, 가격, 소재 등을 표시하는 라벨.'),
    ('shared-term-fashion-retail-019', 'glossary-category-fashion-retail', 'VMD', '비주얼 머천다이징(Visual Merchandising). 매장 진열과 연출로 구매를 유도하는 활동.'),
    ('shared-term-fashion-retail-020', 'glossary-category-fashion-retail', '편집숍', '여러 브랜드의 상품을 한 매장에서 선별해 판매하는 유통 형태.')
on conflict (id) do nothing;
